name: Container-Security-Scan
on:
  push:
    branches: [main]
    paths: ["Dockerfile", ".github/workflows/container-scan.yml"]
  schedule:
    - cron: "0 3 * * 1"  # Mondays 03:00 UTC
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t logsight-scan:ci .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.16.0
        with:
          image-ref: logsight-scan:ci
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      - name: SBOM (SPDX)
        uses: aquasecurity/trivy-action@0.16.0
        with:
          image-ref: logsight-scan:ci
          format: spdx-json
          output: sbom.spdx.json
      - uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: sbom.spdx.json
