# ─────────────────────────────────────────────────────────────
# LogSight-AI • Helm values
# Override any key with: helm install … -f my_values.yaml
# ─────────────────────────────────────────────────────────────

replicaCount: 2

image:
  repository: ghcr.io/trojan3877/logsight
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  LOG_PATH: "/var/log/containers/app.log"
  KAFKA_BROKER: "kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  SNOWFLAKE_ACCOUNT: ""
  SNOWFLAKE_USER: ""
  SNOWFLAKE_PASSWORD: ""
  SNOWFLAKE_DATABASE: "LOGSIGHT"
  SNOWFLAKE_SCHEMA: "PUBLIC"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
